name: Heartbeat
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  signl4:
    runs-on: ubuntu-latest
    name: Heartbeat
    steps:
    - name: webhook
      uses: satak/webrequest-action@master
      id: webhook
      with:
        url: ${{ secrets.SIGNL4_HEARTBEAT_URL }}
        method: POST
        payload: '{"name": "test"}'
    - name: Show Response
      run: echo  "${{ fromJson(steps.webhook.outputs.output).data.data }}"
