name: Heartbeat
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  signl4:
    runs-on: ubuntu-latest
    name: Heartbeat
    steps:
    - name: webhook
      uses: satak/webrequest-action@master
      id: webhook
      with:
        url: https://b58aee12b873eae71b5db8b4fdc77d78.m.pipedream.net
        method: POST
        payload: '{"name": "test"}'
    - name: Show Response
      run: echo  "${{ fromJson(steps.webhook.outputs.output).data.data }}"
