name: Send SIGNL4 Alert
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  signl4:
    runs-on: ubuntu-latest
    name: SIGNL4 Alerting
    steps:
    - name: webhook
      uses: satak/webrequest-action@master
      id: webhook
      with:
        url: https://api.troposphere.io/forecast/52.5200533,13.2966172?token=${{ secrets.TROPOSPHERE_API_KEY }}
        method: GET
    - name: Show Response
      run: echo  "${{ fromJson(steps.webhook.outputs.output).data }}"
    - name: SIGNL4
      uses: signl4/signl4-action-alert@v1.1
      id: signl4
      with:
        team-secret: ${{ secrets.SIGNL4_TEAM_SECRET }}
        title: 'SIGNL4 Alert'
        message: ${{ fromJson(steps.webhook.outputs.output.data).time }}
        X-S4-Service: 'Service'
        X-S4-Location: '52.3984235,13.0544149'
        X-S4-AlertingScenario: 'single_ack'
        X-S4-Filtering: false
        X-S4-ExternalID: 'A1'
        X-S4-Status: 'new'
    - name: Get the output time
      run: echo "SIGNL4 Event ID ${{ steps.signl4.outputs.eventId }}"
